### ISSUE TITLE
Inconsistent @Override annotations in jug.ua.jsonb.impl.gson.GsonJsonbWrapper

### ISSUE THREAD

**Issue by vskh** [sirotae/jsonb-spec-ua-adopt#1]
Compiler complains on @Override annotations on [public <T> T fromJson(String str, Type type)](https://github.com/sirotae/jsonb-spec-ua-adopt/blob/master/ri/src/main/java/jug/ua/jsonb/impl/gson/GsonJsonbWrapper.java#L73) and [public String toJson(Object object, Type type)](https://github.com/sirotae/jsonb-spec-ua-adopt/blob/master/ri/src/main/java/jug/ua/jsonb/impl/gson/GsonJsonbWrapper.java#L121) because there are no methods with such signature in [Jsonb](https://github.com/olegts/jsonb-spec/blob/master/api/src/main/java/javax/json/bind/Jsonb.java) interface.

**Comment by olegts** [comment]
Welcome Vadym,

Yes, to make it work you should use a bit extended Json API lib that you
can find here - https://github.com/olegts/jsonb-spec/tree/generics_mapping
cause unfortunately Spec leads haven't added these method to API yet((

Thank you,
Oleg

2015-04-23 0:08 GMT+03:00 Vadym S. Khondar notifications@github.com:

**Comment by vskh** [comment]
I see, thanks!
